### ISSUE TITLE
Repository service

### ISSUE THREAD

**Issue by gadelkareem** [floriansemm/SolrBundle#150]
Can you explain how do you create a repository service? I could not find it in the docs..

I tried:

```
    app.my_entity_solr_repository:
        class: FS\SolrBundle\Repository\Repository
        factory: ['@solr.client', getRepository]
        arguments:
          - AppBundle\Entity\MyEntity
```
I get an error
```
Warning: Missing argument 1 for AppBundle\Entity\MyEntity::__construct(), called in application/vendor/floriansemm/solr-bundle/FS/SolrBundle/Solr.php on line 149
```

**Comment by Koalabaerchen** [comment]
You need to create the repository class (see https://github.com/floriansemm/SolrBundle#repositories) and then include it via the annotation inside your entity (see https://github.com/floriansemm/SolrBundle#setting-custom-repository-class-with-repository-option)

It's basically like the normal doctrine repositories except that you write solr queries instead of using the querybuilder or writing dql.

**Comment by gadelkareem** [comment]
But is there a way to use it as a service?

**Comment by Koalabaerchen** [comment]
The repository afaik not. Because a repository is different from a service in Symfony.

You can create a service and inject `solr.client` (it's `FS\SolrBundle\Solr`) in the arguments into it. Then continue from there.

**Comment by gadelkareem** [comment]
I digged a bit into the code and I see the instantiation of the entity is important for the [Repository](https://github.com/floriansemm/SolrBundle/blob/0fe01baad28b8ffa3f72bed86ef41195345bb682/Solr.php#L141) and other services but it might be avoided as far it is only used to read the annotations in [\FS\SolrBundle\Doctrine\Mapper\MetaInformationFactory::loadInformation](https://github.com/floriansemm/SolrBundle/blob/0fe01baad28b8ffa3f72bed86ef41195345bb682/Doctrine/Mapper/MetaInformationFactory.php#L45). What do you think?

**Comment by Koalabaerchen** [comment]
Oh, I didn't see the edit in your first posting.

Can you post your constructor of your service?

**Comment by gadelkareem** [comment]
You mean the Entity?
```
class MyEntity
{
   public function __construct($title, $url)
   {
        $this->title = trim($title);
        $this->url = trim($url);
        $this->dateCreated = new \DateTime();
    }
}
```

**Comment by floriansemm** [comment]
@gadelkareem to fix your issue you can set default-constructor parameters:

```public function __construct($title = '', $url = '')```

But your are right. It is a good idea to remove the entity dependency from the repository-class.

**Comment by gadelkareem** [comment]
Thank you! is it possible to introduce this improvement any soon?

**Comment by floriansemm** [comment]
I am working on it

**Comment by floriansemm** [comment]
the [lastest release](https://github.com/floriansemm/SolrBundle/tree/v1.6.5) includes some refactorings which solves your issue

**Comment by gadelkareem** [comment]
Thank you! would the repository service config I posted earlier still work?
```
    app.my_entity_solr_repository:
        class: FS\SolrBundle\Repository\Repository
        factory: ['@solr.client', getRepository]
        arguments:
          - AppBundle\Entity\MyEntity
```
