### ISSUE TITLE
Loading fixtures does not work

### ISSUE THREAD

**Issue by dkorsak** [floriansemm/SolrBundle#39]
I have Symfony 2.1.x configured with Doctrine2

My solr configuration

```
fs_solr:
    solr:
        hostname: localhost
        port: 8983
        path:
            core0: /admin/solr-test
    auto_index: true
    entity_manager: default
```

When I'm trying to load my fixtures there is error:

```
Catchable Fatal Error: Argument 1 passed to FS\SolrBundle\Doctrine\MongoDB\Listener\AddDocumentListener::postPersist() 
must be an instance of Doctrine\ODM\MongoDB\Event\LifecycleEventArgs, 
instance of Doctrine\ORM\Event\LifecycleEventArgs given, called in /../vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php on line 61 
and defined in /.../vendor/floriansemm/solr-bundle/FS/SolrBundle/Doctrine/MongoDB/Listener/AddDocumentListener.php line 26 
```

I think when my ORM is configured to use Doctrine2 then bundles should only add listeners for Doctrine2 not Doctrine Mongo
