### ISSUE TITLE
solr.client keeps searching in default core

### ISSUE THREAD

**Issue by SrgSteak** [floriansemm/SolrBundle#99]
Config:

```yaml
fs_solr:
    endpoints:
        core0:
            host: localhost
            port: 8983
            path: /solr
            core: archyAsset
            timeout: 5
        core1:
            host: localhost
            port: 8983
            path: /solr
            core: archyTag
            timeout: 5
```

Entity:

```php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FS\SolrBundle\Doctrine\Annotation as Solr;

/**
 * @Solr\Document(index="core1", repository="AppBundle\Entity\Tag")
 * @ORM\Table()
 * @ORM\Entity
 */
class Tag
{
    /**
     * @var int
     * @Solr\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Solr\Field(type="string")
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

// and so on
```

Controller:

```php
//....
$tag_query = $this->get('solr.client')->createQuery('AppBundle:Tag');
$tag_query->queryAllFields('searchWord');
$tags = $tag_query->getResult();

return array('tags' => $tags);
//....
```

But the Solr log returns:
77621030 [qtp1355316001-14] INFO  org.apache.solr.core.SolrCore  – [archyAsset] webapp=/solr path=/select params={q=title_s:*searchWord*+OR+description_t:*searchWord*+OR+id:*searchWord*&json.nl=flat&omitHeader=true&fl=*,score&start=0&rows=10&wt=json} hits=0 status=0 QTime=3 

If i switch the config to:
```yaml
fs_solr:
    endpoints:
        core1:
            host: localhost
            port: 8983
            path: /solr
            core: archyTag
            timeout: 5
        core0:
            host: localhost
            port: 8983
            path: /solr
            core: archyAsset
            timeout: 5
```

It uses the first core. I also tried the indexHandler (wich gets called) but there's no difference.
```
app/console solr:synchronize AppBundle:Tag
```
Always adds infos to the correct core.

Any Ideas why?
